# Generated by Django 2.1.3 on 2018-11-06 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contactbox', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='address',
            field=models.ManyToManyField(related_name='user', to='contactbox.Address'),
        ),
        migrations.AlterField(
            model_name='user',
            name='group',
            field=models.ManyToManyField(related_name='users', to='contactbox.Group'),
        ),
    ]
